### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by SebCanet** [fontainejp/blocklino#1]
On a fresh Windows 7 install, I followed everything but I had problems:
VS components not totally installed on a computer,
![image 1](https://user-images.githubusercontent.com/6362199/51842096-6ad05d80-2310-11e9-874e-89f2fb3dafb4.jpg)
electron-rebuild not installing when I type 'npm install'
![image 2](https://user-images.githubusercontent.com/6362199/51844064-aec56180-2314-11e9-8d90-4e9910d0268d.jpg)

Any help please ?

**Comment by SebCanet** [comment]
Fixed by updating serialport to 7.1.4 in package.json

**Comment by SebCanet** [comment]
Compiling seems ok but when trying to build:
![image](https://user-images.githubusercontent.com/6362199/52312299-63612200-29aa-11e9-8235-e2a0c6939e6c.png)

**Comment by fontainejp** [comment]
try with new pakage.json ?

**Comment by SebCanet** [comment]
I'm trying...but seems to block on serialport downloading. Really need v7.1.4 for windows install command.

**Comment by SebCanet** [comment]
Still have serialport version pb.
Next on #3
