### ISSUE TITLE
Problem with codebender

### ISSUE THREAD

**Issue by cparrapa** [fontainejp/blocklino#5]
Hi

First great work with this blockly!

I am just having problem to upload codes into my nano clone (CH340 driver), from the web version in my PC,  even after installed the plugin https://codebender.cc/static/plugin  (Arduino Create Agent)  i cannot see the board connected.

Thanks in advance

**Comment by fontainejp** [comment]
Hi
Thanks !
You can use codebender with firefox but since version 46 it's impossible because codebender became paid (before it was free)
So you can just create your programm and save it if firefox is older than 46.
Sorry :-(

**Comment by cparrapa** [comment]
Oh what a pity well i like the offline version more but i need to learn how to build the .exe.
And are you thinking to release for MAC?

Thanks!
