### ISSUE TITLE
npm start and compile error

### ISSUE THREAD

**Issue by cparrapa** [fontainejp/blocklino#6]
Hi 
When i do npm start a white window appear and nothing happens,

PS C:\WINDOWS\system32\blocklino> npm start

> Blocklino@1.4.0 start C:\WINDOWS\system32\blocklino
> electron .

 **i also tried to compile** 

PS C:\WINDOWS\system32\blocklino> npm run compilerblocklino\node_modules\electron\dist\electron.exe path-to-app
npm ERR! missing script: compilerblocklino\node_modules\electron\dist\electron.exe

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Camilo\AppData\Roaming\npm-cache\_logs\2019-08-26T10_38_32_304Z-debug.log
PS C:\WINDOWS\system32\blocklino> npm run compiler

> Blocklino@1.4.0 compiler C:\WINDOWS\system32\blocklino
> build --win --ia32

Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.39.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=C:\WINDOWS\system32\dist\builder-effective-config.yaml
  • rebuilding native production dependencies platform=win32 arch=ia32
  • packaging       platform=win32 arch=ia32 electron=4.1.1 appOutDir=C:\WINDOWS\system32\dist\win-ia32-unpacked
  • downloading               parts=8 size=58 MB url=https://github.com/electron/electron/releases/download/v4.1.1/electron-v4.1.1-win32-ia32.zip
  • downloaded                duration=46.514s url=https://github.com/electron/electron/releases/download/v4.1.1/electron-v4.1.1-win32-ia32.zip
  • downloading               parts=1 size=5.6 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
  • downloaded                duration=7.592s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.4.0/winCodeSign-2.4.0.7z
Error: Exit code: 1. Command failed: C:\Users\Camilo\AppData\Local\electron-builder\Cache\winCodeSign\winCodeSign-2.4.0\rcedit-ia32.exe C:\WINDOWS\system32\dist\win-ia32-unpacked\Blocklino.exe --set-version-string FileDescription Blocklino --set-version-string ProductName Blocklino --set-version-string LegalCopyright Copyright © 2019 Fontaine Jean Philippe --set-file-version 1.4.0 --set-product-version 1.4.0.0 --set-version-string InternalName Blocklino --set-version-string OriginalFilename  --set-version-string CompanyName Fontaine Jean Philippe --set-icon C:\WINDOWS\system32\blocklino\build\app.ico
Cannot open icon file 'C'
Fatal error: Unable to set icon

Cannot open icon file 'C'
Fatal error: Unable to set icon

    at C:\Windows\System32\blocklino\node_modules\builder-util\src\util.ts:126:16
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
From previous event:
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.signAndEditResources (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\winPackager.ts:260:158)
    at _bluebirdLst.default.map.file (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\winPackager.ts:363:21)
    at go$readdir$cb (C:\Windows\System32\blocklino\node_modules\graceful-fs\graceful-fs.js:187:14)
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\winPackager.ts:361:27
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\winPackager.ts:355:73)
    at C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\platformPackager.ts:250:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Windows\System32\blocklino\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at callback (C:\Windows\System32\blocklino\node_modules\graceful-fs\polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Windows\System32\blocklino\node_modules\graceful-fs\graceful-fs.js:136:16
    at C:\Windows\System32\blocklino\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Windows\System32\blocklino\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Windows\System32\blocklino\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Windows\System32\blocklino\node_modules\electron-builder\src\cli\cli.ts:46:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Blocklino@1.4.0 compiler: `build --win --ia32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Blocklino@1.4.0 compiler script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Camilo\AppData\Roaming\npm-cache\_logs\2019-08-26T10_40_20_534Z-debug.log
PS C:\WINDOWS\system32\blocklino> npm start

> Blocklino@1.4.0 start C:\WINDOWS\system32\blocklino
> electron .

**Comment by fontainejp** [comment]
Hi
1 : you have nodejs installed ?
2 : blocklino is on C:\WINDOWS\system32\ ?
3 : in folder C:\WINDOWS\system32\blocklino\build\
there are 
app.ico 
file.ico 
blocklino.nsh 
install.ico and license.txt ?
Because the log says "Cannot open icon file 'C' Fatal error: Unable to set icon "

**Comment by fontainejp** [comment]
Hi 
and after npm install ?
it's ok ?

**Comment by cparrapa** [comment]
Hi 
1. node.js i have i use for react native.
2. yes blocklino is in  C:\WINDOWS\system32\ 
3. i see the files there

npm install no problems but i had to use Windows PowerShell instead of git bash
Thanks

**Comment by fontainejp** [comment]
Hi
sorry but I'm busy right now. I'll look at that a bit later.

**Comment by fontainejp** [comment]
Hi,
i try with powershell and it's ok for me .
Can you try :
npm ls --depth=0
in C:\WINDOWS\system32\blocklino\
Have you try to put blocklino in another directory ?

**Comment by cparrapa** [comment]
Hi 
I will try to move to another folder then 
thanks!

**Comment by cparrapa** [comment]
Hi 
i tried again using git bash and in another directory C:\Users\Camilo\blocklino

Everything seems ok after npm install
but when npm start i just see a white screen

 $ npm ls --depth=0
Blocklino@1.5.0 C:\Users\Camilo\blocklino
+-- ajv@6.10.0
+-- child_process@1.0.2
+-- electron@4.1.1
+-- electron-builder@20.39.0
+-- electron-updater@4.0.6
`-- serialport@7.1.4

Am i missing one step?
is it possible to contribute without build? i just want to do quick test add new blocks, components and have the .exe ready to use.
Thanks

**Comment by fontainejp** [comment]
Sorry, but all seems ok :-(
you can download the last release (zip)
unzip 
go to www\blocs&generateurs
add your code in a js file 
go to www\toolbox
add your code in a xml file 
restart blocklino

**Comment by cparrapa** [comment]
Hi
I see i also want to help you with the translation to English and maybe Spanish in the future where to do it?

**Comment by fontainejp** [comment]
ok thanks
for translation go to www\lang
edit code.js
create or edit msg_ blockly_ and arduino_ (about 90%)
few things in html files
and js files in resources directory

**Comment by cparrapa** [comment]
Hi @fontainejp 

1. So translation i thought it was missing for English and i only in some areas, the "verifier, televerser and exporter les binaries" buttons in the top bar and the level names but i did not find them in the lang folder. I also noticed that to be able to change language you need to close and open again the software can this be improved?

2. I manage to add toolbar for the new blocks by modifying toolbox_arduino_all.xml and actually i had to modify also the \lang\Arduino_en.js file, to see them i have to select level "confirme"

3. For the generator i have problems i am not sure where to put the code exactly:
arduino_blocs.js or arduino_generateurs_cpp.js or both and how to divide?

Thanks

**Comment by fontainejp** [comment]
Hi,
1 - english is quite good refresh with F5, found a new bug ;-)
verifier... is in www\js\blocklino.js (to do : change for translation)
2 - if you want to add a new level go to www\index.html line 223 (to do : change for translation)
3 - att th beginning there was 2 files (1 for blocks and 1 for code) and now i put all codes in the same files (for exemple : 
`Blockly.Blocks["lp2i_mp3_play_track"]={init:function(){
    this.appendValueInput("num", "Number").appendField(new Blockly.FieldImage("data:image/png;base64,iVBORlCI..........", 11, 15))
		.appendField(Blockly.Msg.lp2i_mp3_play+" n°");
    this.setInputsInline(false);
    this.setPreviousStatement(true, null);
    this.setNextStatement(true, null);
    this.setColour("#00929F");
    this.setTooltip(Blockly.Msg.lp2i_mp3_play_track_tooltip);
    this.setHelpUrl(Blockly.Msg.lp2i_mp3_helpurl)}
};
Blockly.Arduino["lp2i_mp3_play_track"]=function(block){
	var piste=Blockly.Arduino.valueToCode(block, "num", Blockly.Arduino.ORDER_ATOMIC);
    return "exe_cmd(0x03,0,"+piste+");\ndelay(500);\n"
};
Blockly.Python["lp2i_mp3_play_track"]=function(block){
	var piste=Blockly.Python.valueToCode(block, "num", Blockly.Python.ORDER_ATOMIC);
    return "mp3.PlaySpecific("+piste+")\n"
};`
hope it helps you

**Comment by cparrapa** [comment]
Hi 
1. I made a pull request.
2. I actually want to take out the levels ;) and have only one list to select from.
3. Trying now to modify blockly.blocs.js

Thanks!
