### ISSUE TITLE
White screen after built

### ISSUE THREAD

**Issue by cparrapa** [fontainejp/blocklino#8]
Hi @fontainejp 

Happy new year!
I actually manage ( i think) to build the app but after is built and i open the .exe only a white screen appears, why is this happening?

Thanks

**Comment by fontainejp** [comment]
Hi , 
Thanks ;-)
many things can happen
Type F8 it will open the JS console and copy/paste the errors
you can verify blocklino's directory 
resources
  app
    electronApp.js ---> the first most important
www
  index.html ---> the second most important

**Comment by cparrapa** [comment]
Thanks i will try and check but which one should be used for building the app:
Blocklino-1.6.0-ia32-win.zip or the from the Source code(zip) ?

**Comment by fontainejp** [comment]
download https://github.com/fontainejp/blocklino/archive/master.zip (the source code)
unzip 
download and install node/npm
go in blocklino's folder
npm install -g windows-build-tools
npm install
npm run compiler (for windows only)
go in ../dist

**Comment by cparrapa** [comment]
now it seems magically working althought i got this message after npm install -g windows-build-tools
Could not install Visual Studio Build Tools.
Please find more details in the log files, which can be found at
C:\Users\Camilo\.windows-build-tools

BTW in this new 1.7 version when change the font size in settings there is a bug that divide the screen and reduce the toolbar

**Comment by fontainejp** [comment]
for the bug can you take a screenshot please
sometimes when we switch code/block the workspace disappear  --> resize the window and it's ok
to install npm modules you have to open the terminal in admin mode

**Comment by cparrapa** [comment]
i open in admin one time work and now after npm install i get this
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Blocklino@1.7.0 compiler: `build --win --ia32`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Blocklino@1.7.0 compiler script.
npm ERR! This is probably not a problem with npm. There is likely additional log                   ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Camilo\AppData\Roaming\npm-cache\_logs\2020-01-13T14_38_08                   _267Z-debug.log

**Comment by cparrapa** [comment]
ok fixed that seems ok is just that sometimes does not load the toolbar is a little strange.
And it does not compile for arduino, when press check this appear
Error: Command failed: verify.bat nano open C:\Users\Camilo\Documents\Software\dist\win-ia32-unpacked\compilation\arduino\tools-builder: The system cannot find the file specified.
